### ISSUE TITLE
Deploy to Vercel button

### ISSUE THREAD

**Issue by leerob** [dolapay/backendless-ecommerce-platform#2]
This is really awesome! I've love to see a deploy button to automate the process of getting this deployed. Would really improve the getting started experience 😄

**Comment by Phunmbi** [comment]
Thanks very much @leerob , 100% agree, we'll get right on that for the next release.

**Comment by leerob** [comment]
Amazing 😄  https://vercel.com/docs/more/deploy-button

**Comment by Phunmbi** [comment]
@leerob We've now added a deploy button to a BEP + NextJS + Typescript starter kit [here](https://github.com/dolapay/backendless-ecommerce-platform/tree/master/examples/nextjs-example)

**Comment by Phunmbi** [comment]
The examples and starter kits now get their own [repo](https://github.com/dolapay/bep-examples). The next starter can now be found [here](https://github.com/dolapay/bep-examples/tree/main/with-next)
